org: wenndder
app: aws-code-challenge
service: code-challenge-stefanini

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  createEmployee:
    handler: src/routes/employees/createEmployee.createEmployee
    events:
      - httpApi:
          path: /employee
          method: post

  updateEmployee:
    handler: src/routes/employees/updateEmployee.updateEmployee
    events:
      - httpApi:
          path: /employee/{id}
          method: put

  deleteEmployee:
    handler: src/routes/employees/deleteEmployee.deleteEmployee
    events:
      - httpApi:
          path: /employee/{id}
          method: delete

  getEmployee:
    handler: src/routes/employees/getEmployee.getEmployee
    events:
      - httpApi:
          path: /employee/{id}
          method: get